ENG-2744 - Added workspace cleanup step after job execution
xebialabs/xl-docker-images pull request #70
Opened 2020-11-24 02:53 UTC by karthiksonti24

## Definition of Done

**General**
 - [ ] Branch is up-to-date with master
 - [ ] Code is reviewed and tested by someone in the Kube team
 - [ ] If there are user facing changes (new env variables for example) update the docs and make sure to notify the docs team to update official documentation

2020-11-24 07:04 UTC, barathisukumar approved these changes

2020-11-24 07:13 UTC, barathisukumar requested changes
Came across this regarding deleteDir() - https://issues.jenkins.io/browse/JENKINS-41894 which could cause potential problems in docker context. Can you check this ?

2020-11-25 05:39 UTC, karthiksonti24 commented
> Came across this regarding deleteDir() - https://issues.jenkins.io/browse/JENKINS-41894 which could cause potential problems in docker context. Can you check this ?

moved to cleanWs().

2020-12-08 10:02 UTC, barathisukumar approved these changes

2020-12-08 10:04 UTC, merged